### ISSUE TITLE
Problem executing bytecode executable, starting from 4.07.0+mingw32c version (cygwin/mingw environment)

### ISSUE THREAD

**Issue by bjeannet** [yallop/ocaml-integers#28]
Environment: opam 2.03, ocaml version 4.08.0+mingw32c, integers version 0.3.0 
1. The problem: compiling
>
let _ =
  let x = Unsigned.UInt16.of_int 2 in
  Format.printf "%i@." (Unsigned.UInt16.to_int x);
  ()
>
with `ocamlfind ocamlc -o t.exe t.ml -package integers -linkpkg`
and executing with `./t.exe`gives the following message:
>
Fatal error: cannot load shared library dllintegers_stubs
Reason: The specified module could not be found.
>
2. Investigating the problem by executing `strace ./t.exe`results in
>
[...]
--- Process 17020 loaded C:\Users\bjt2\.opam\4.08.0+mingw32c\lib\stublibs\dllintegers_stubs.dll at 6cf80000
--- Process 17020 unloaded DLL at 6cf80000
--- Process 17020 loaded C:\Users\bjt2\.opam\4.08.0+mingw32c\lib\stublibs\dllintegers_stubs.dll at 6cf80000
--- Process 17020 unloaded DLL at 6cf80000
--- Process 17020 thread 2428 exited with status 0x2
>
The library is found but something strange happens.

3. The example above works fine with version 4.06.0+mingw32c, the problem appears starting from version 4.07.0+mingw32c. (I tested 4.06.0, 4.07.0, 4.07.1, 4.08.0). Switching to integers version 0.2.2 does not change anything.

4. I have no such problem with other libraries depending on DLLs like zarith.

5. Native compilation works fine however.

**Comment by fdopen** [comment]
It's a consequence of https://github.com/ocaml/ocaml/pull/1535

You have to add the path with the dlls of gcc to your PATH (`/usr/i686-w64-mingw32/sys-root/mingw/bin` or `/usr/x86_64-w64-mingw32/sys-root/mingw/bin` in the case of cygwin, `i686-w64-mingw32-objdump.exe -p $(opam config var lib)/stublibs/dllintegers_stubs.dll | grep 'DLL Name'` should list the dll dependencies).

I've worked around the issue for ctypes in https://github.com/ocamllabs/ocaml-ctypes/pull/586/commits/4750aef48d797673ae213d2268ca79a0692fe220

In this commmit I've passed '-ldopt -link -ldopt -static-libgcc' to ocamlmklib, when building the dll, but not to ocamlopt when building the 'cmxa' file. In the case of dune, there don't seem to be an option to pass specific flags just to ocamlmklib, but not to ocamlopt. So I don't know, how to fix it.

(If you don't care about c++-exceptions, you can always enforce the old behaviour with `FLEXLINKFLAGS='-link -static-libgcc' opam reinstall offending-package` ...)

**Comment by bjeannet** [comment]
Thank you very much for the help and the explanations.
We don’t care about c++ exceptions, so your suggestion is perfect and works fine.
I found quite subtle that gcc DLLs are required for 2/3 basic arithmetic functions, and only in 32 bits !

Cordialement / Best Regards,

Bertrand JEANNET

Argosim Architecture R&D



bertrand.jeannet@3ds.com <mailto:Bertrand.JEANNET@3ds.com>
3DS.COM/CATIA <http://www.3ds.com/CATIA>

[cid:image005.png@01D55682.9D382FA0]

ARGOSIM | de Mayencin, | 38400 Saint Martin d’Heres | France

**Comment by anentropic** [comment]
I found this issue via googling for the error I'm getting: `Fatal error: cannot load shared library dllintegers_stubs`

But I am on macOS, ocaml 4.12 and get the error when I try to use `ocamldebug`:

```
ocamldebug _build/default/bin/cli.bc
    OCaml Debugger version 4.12.0

(ocd) r
Loading program... Fatal error: cannot load shared library dllintegers_stubs
Reason: dlopen(dllintegers_stubs.so, 10): image not found
(ocd)
```

more info here https://stackoverflow.com/questions/68335022/fatal-error-cannot-load-shared-library-dllintegers-stubs

my project builds fine under dune, it's with the debugger that I get this problem
