### ISSUE TITLE
C interface question

### ISSUE THREAD

**Issue by shindere** [yallop/ocaml-integers#50]
Sorry for the likely naïve question but, how to use this package
in the context of an interface with C?

To be more concrete, I'd like to provide `htonl` and `ntohl` in OCaml
but I am unsure how to do the conversions between values of the
`Integers.uint32` OCaml type and values of the `uinT3_t` C type.

Is this either documented somewhere and I missed it or so trivial
that it's not even worth a documentation?

Many thanks in advance for any help.

**Comment by yallop** [comment]
The C interface is in [`ocaml_integers.h`](https://github.com/yallop/ocaml-integers/blob/master/src/ocaml_integers.h).  For example, you can use [`integers_copy_uint32`](https://github.com/yallop/ocaml-integers/blob/6aaa3e3d6e9bd52e9afa433de38d8c69debc97eb/src/ocaml_integers.h#L18C7-L19C51) and [`Uint32_val`](https://github.com/yallop/ocaml-integers/blob/6aaa3e3d6e9bd52e9afa433de38d8c69debc97eb/src/ocaml_integers.h#L31) to convert between `Integers.uint32` and `uint32_t`.

If you're using ctypes, then the [`Ctypes.uint32_t`](https://ocaml.org/p/ctypes/0.23.0/doc/Ctypes/index.html#val-uint32_t) value will perform the conversion for you.

**Comment by shindere** [comment]
Thanks a lot for the very helpful response.
For some reason, I didn't see this header file.

Feel free to close this issue.
